name: 'Deploy to aws s3'
description: 'deploy a static website in aws'
inputs:
  bucket: 
    description: 'The s3 bucket name'
    required: true
  bucket-region: 
    description: 'region of s3 bucket'
    required: false
    default: 'us-east-1'
  dist-folder:
    description: 'folder containing deployable files'
    required: true
runs:
  using: 'node20'
  main: 'main.js'